name: Update Version File

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate and push version file without cloning
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_SHA: ${{ github.sha }}
          GH_REPO: ${{ github.repository }}
        run: |
          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git remote add origin "https://x-access-token:${GH_TOKEN}@://github.com{GH_REPO}.git"
          
          git fetch --depth=1 origin main
          git checkout main

          echo "$COMMIT_SHA" > version

          git add version
          git commit -m "chore: update version file to hash $COMMIT_SHA"
          git push origin main

      - name: Purge jsDelivr cache
        env:
          GH_REPO: ${{ github.repository }}
        run: |
          curl -s "https://jsdelivr.net{GH_REPO}@latest/version"
